on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "git@github.com:mfandl/hml.git"
        source_branch: "refs/remotes/source/*"
        destination_repo: "git@gitlab.matfyz.sk:mfandl/hml_sync.git"
        destination_branch: "refs/heads/*"
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
